default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ejb52940.us-east-1
      user: HSIJ
      password: xxx
      role: NOVO_NORDISK_STUDENT
      database: NOVO_NORDISK
      warehouse: NOVO_NORDISK
      schema: DBT_AKKSHAYA
      threads: 4
