version: 2

sources:
  - name: northwind
    database: northwind  
    schema: raw_northwind
    tables:
      - name: _order_
      - name: customer
      - name: product
      - name: orderdetail
      - name: orders_full
